name: build

on:
    push:
        branches: [main]
        paths-ignore:
            - "docs/**"
            - Makefile
            - README.md
    pull_request:
        branches: [main]
        paths-ignore:
            - "docs/**"
            - Makefile
            - README.md
    workflow_dispatch:

defaults:
    run:
        shell: bash

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "stable"

            - name: Test and build
              run: make test build

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: codapi
                  path: build/codapi
                  retention-days: 7
